#! /bin/sh

# config.sh.in 

# This file is processed by config.status to produce config.status,
# containing autoconf-determined values needed by the test scripts.

ECHO_T=""
ECHO_N="-n"
ECHO_C=""
HOST_OS="linux-gnu"
SHELL_PATH="/bin/sh"
FAKEROOT_PATH="/usr/bin/fakeroot"

export ECHO_T ECHO_N ECHO_C HOST_OS SHELL_PATH FAKEROOT_PATH
